const submissions = [
  {
    id: 1,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 16,
    avatar: "https://bulma.io/images/placeholders/128x128.png",
    submissionImage: "https://bulma.io/images/placeholders/24x24.png",
  },
  {
    id: 2,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 39,
    avatar: "https://bulma.io/images/placeholders/128x128.png",
    submissionImage: "https://bulma.io/images/placeholders/24x24.png",
  },
  {
    id: 3,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 21,
    avatar: "https://bulma.io/images/placeholders/128x128.png",
    submissionImage: "https://bulma.io/images/placeholders/24x24.png",
  },
  {
    id: 4,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 6,
    avatar: "https://bulma.io/images/placeholders/128x128.png",
    submissionImage: "https://bulma.io/images/placeholders/24x24.png",
  },
  {
    id: 5,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 10,
    avatar: "https://bulma.io/images/placeholders/128x128.png",
    submissionImage: "https://bulma.io/images/placeholders/24x24.png",
  },
];
